{"name": "test_user_authorization_negative_wrong_passw", "status": "failed", "statusDetails": {"message": "AssertionError: current url should be not https://target.my.com/dashboard", "trace": "self = <test_login.TestLogin object at 0x7fb4158d6a60>\n\n    @allure.epic(\"Авторизация\")\n    @allure.feature(\"Ошибка авторизации при неккоректных данных\")\n    @allure.story(\"Переход на сайт для ввода корректных данных\"\n                  \"при ошибке ввода пароля\")\n    @pytest.mark.UI\n    def test_user_authorization_negative_wrong_passw(self):\n        self.login_page.should_be_open_login_form_button()\n        self.login_page.open_login_form()\n        self.login_page.should_be_login_form()\n        self.main_page = self.login_page.login(USERNAME, PASSWORD)\n>       self.main_page.should_be_wrong_url()\n\ntest_login.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <ui.pages.main_page.MainPage object at 0x7fb4158a0970>\n\n    @allure.step(\"Проверка на несовпадение url c текущим\")\n    def should_be_wrong_url(self):\n>       assert self.url != self.driver.current_url, f'current url should be not {self.url}'\nE       AssertionError: current url should be not https://target.my.com/dashboard\n\nui/pages/base_page.py:53: AssertionError"}, "steps": [{"name": "Ожидание появления кнопки для открытия формы авторизации", "status": "passed", "start": 1648648331478, "stop": 1648648334737}, {"name": "Клик по кнопке 'Войти'", "status": "passed", "start": 1648648334737, "stop": 1648648334907}, {"name": "Ожидание появления формы авторизации", "status": "passed", "start": 1648648334907, "stop": 1648648334952}, {"name": "Заполнение полей email и password", "status": "passed", "parameters": [{"name": "username", "value": "'doychevvs@gmail.com'"}, {"name": "password", "value": "'uP@!_J-azC2Z!bg'"}], "start": 1648648334952, "stop": 1648648337578}, {"name": "Проверка на несовпадение url c текущим", "status": "failed", "statusDetails": {"message": "AssertionError: current url should be not https://target.my.com/dashboard\n", "trace": "  File \"/usr/local/lib/python3.8/dist-packages/allure_commons/_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"/home/doychevvs/vk/2022-1-QAPYTHON-VK-V-Doychev/homework2/ui/pages/base_page.py\", line 53, in should_be_wrong_url\n    assert self.url != self.driver.current_url, f'current url should be not {self.url}'\n"}, "start": 1648648337579, "stop": 1648648337594}], "attachments": [{"name": "log", "source": "ede49382-3037-4477-b5ad-bf87ea1b2e33-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c85dfcd2-0ca0-4ab0-8247-7bb5db4b368e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "293017bf-0183-4c22-9e4b-ea07c767db01-attachment.txt", "type": "text/plain"}], "start": 1648648331477, "stop": 1648648337595, "uuid": "9d8aadf7-f5da-43e6-9e3e-e171614954c3", "historyId": "cdd4f56f77b8bc42116137c16762d475", "testCaseId": "34c5c67863ac46b690bf17728ceef975", "fullName": "test_login.TestLogin#test_user_authorization_negative_wrong_passw", "labels": [{"name": "epic", "value": "Авторизация"}, {"name": "feature", "value": "Ошибка авторизации при неккоректных данных"}, {"name": "story", "value": "Переход на сайт для ввода корректных данныхпри ошибке ввода пароля"}, {"name": "tag", "value": "UI"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "doychevvs"}, {"name": "thread", "value": "10160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}